### ISSUE TITLE
Missing files after recent commit

### ISSUE THREAD

**Issue by luizfelippesr** [hammurabi-dev/hammurabiX#8]
After 676ecb6 I cannot build hammurabi any more: the files: `source/field/b/breg_cart.cc` and `field/b/breg_helix.cc` are missing.

**Comment by gioacchinowang** [comment]
@ashley-stock Hey Ashley, are these two files missing in your previous commits?

**Comment by ashley-stock** [comment]
@gioacchinowang It appears so. I've added them now.
